name: Docker build

on:
    push
env:
    Container_registry: docker.io
    docker_username: koushikn23
    docker_passwd: ${{ secrets.DOCKER_PASSWD }}
    Image_name: netflix

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: docker build
              run: echo docker build -t $Container_registry/$docker_username/$Image_name:latest
            
            - name: Docker login
              run: echo docker login --username=$docker_username --password=$docker_passwd
            
            - name: docker publish
              run: echo docker push -t $Container_registry/$docker_username/$Image_name:latest